<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'Settings'                     => 'Impostazioni'                , 
	'LBL_SEARCH_SETTINGS_PLACEHOLDER' => 'Impostazioni ricerca'             , // TODO: Review
	'LBL_SUMMARY'                  => 'Sommario'                     , // TODO: Review
	'LBL_ACTIVE_USERS'             => 'Utenti'                       , // TODO: Review
	'LBL_WORKFLOWS_ACTIVE'         => 'Workflows'                   , // TODO: Review
	'LBL_MODULES'                  => 'Moduli'                     , // TODO: Review
	'LBL_SETTINGS_SHORTCUTS'       => 'Scorciatoie impostazioni'          , // TODO: Review
	'LBL_UNPIN'                    => 'Unpin'                       , // TODO: Review
	'LBL_PIN'                      => 'pin'                         , // TODO: Review
	'LBL_STUDIO'                   => 'Studio'                      , 
	'LBL_COMMUNICATION_TEMPLATES'  => 'Template Comunicazione'      , 
	'LBL_USER_MANAGEMENT'          => 'Gestione Utenti e Accessi'   , 
	'LBL_ACCESS_MANAGEMENT'        => 'Gestione accessi'           , 
	'LBL_MODULE_MANAGER'           => 'Gestione modilui'           , 
	'LBL_NOTIFICATIONS'            => 'Notifiche'               , 
	'LBL_EXTERNAL_SERVER_SETTINGS' => 'Impostazioni server esterno'    , 
	'LBL_OTHER_SETTINGS'           => 'Altre Impostazioni'          , 
	'LBL_EXTENSIONS_PLACE'         => 'Extensions Place'            , // TODO: Review
	'LBL_EXTENSIONS'               => 'Extensioni'                  , // TODO: Review
	'LBL_DESCRIPTION'              => 'Descrizione'                 , // TODO: Review
	'LBL_USER_DESCRIPTION'         => 'Gestisce gli Utenti che possono accedere a vTiger CRM', 
	'LBL_ROLES'                    => 'Ruoli'                       , 
	'LBL_ROLE_DESCRIPTION'         => 'Definisce una Gerarchia di Ruoli e la assegna agli Utenti', 
	'LBL_PROFILES'                 => 'Profili'                     , 
	'LBL_PROFILE_DESCRIPTION'      => 'Gestisce l\'accesso specifico di un Utente a Ruoli differenti', 
	'USERGROUPLIST'                => 'Gruppi'                      , 
	'LBL_GROUP_DESCRIPTION'        => 'Gestisce differenti Gruppi basati sui ruoli, utenti e profili', 
	'LBL_SHARING_ACCESS'           => 'Accesso Condiviso'           , 
	'LBL_SHARING_ACCESS_DESCRIPTION' => 'Gestisce Regole di condivisione & condivisione personalizzata dei moduli', 
	'LBL_WORKFLOW_LIST'            => 'Lista Workflow'               , 
	'LBL_AVAILABLE_WORKLIST_LIST'  => 'Imposta dipendenza tra i valori delle picklist in ogni modulo', 
	'LBL_FIELDFORMULAS'            => 'Formule campi'               , 
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Aggiungi una forumula ai campi personalizzati', 
	'VTLIB_LBL_MODULE_MANAGER'     => 'Gestore moduli'              , 
	'VTLIB_LBL_MODULE_MANAGER_DESCRIPTION' => 'Gestisci il comportamento del modulo all&#39;interno del CRM vtiger', 
	'LBL_PICKLIST_EDITOR'          => 'Editor di Picklist'          , 
	'LBL_PICKLIST_DESCRIPTION'     => 'Personalizza i valori delle Picklist in ciascun modulo', 
	'LBL_PICKLIST_DEPENDENCY_SETUP' => 'Picklist Dependency Setup'   , 
	'LBL_PICKLIST_DEPENDENCY_DESCRIPTION' => 'Imposta dipendenza tra le picklist in ogni modulo', 
	'LBL_MENU_EDITOR'              => 'Menu Editor'                 , 
	'LBL_MENU_DESC'                => 'Imposta sequenza menu'     , 
	'EMAILTEMPLATES'               => 'Template Email'              , 
	'LBL_EMAIL_TEMPLATE_DESCRIPTION' => 'Gestisce i template per il modulo Email', 
	'LBL_COMPANY_DETAILS'          => 'Dettagli Societ&agrave;'     , 
	'LBL_COMPANY_DESCRIPTION'      => 'Specifica l\'indirizzo e i dati dell\'azienda', 
	'LBL_MAIL_MERGE'               => 'Unione Mail'                  , 
	'LBL_MAIL_MERGE_DESCRIPTION'   => 'Gestisce template per Unione Email', 
	'LBL_TAX_SETTINGS'             => 'Calcolo delle Tasse'         , 
	'LBL_TAX_DESCRIPTION'          => 'Gestisce le tasse e le percentuali di tassazione', 
	'LBL_MAIL_SERVER_SETTINGS'     => 'Server in Uscita'            , 
	'LBL_MAIL_SERVER_DESCRIPTION'  => 'Cambia le impostazioni per il Server di Posta in Uscita', 
	'INVENTORYTERMSANDCONDITIONS'  => 'Inventario: Termini e Condizioni', 
	'LBL_INV_TANDC_DESCRIPTION'    => 'Specifica Termini e Condizioni per Preventivi, Ordini e Fatture', 
	'LBL_ANNOUNCEMENT_DESCRIPTION' => 'Gestisci gli annunci aziendali', 
	'LBL_CURRENCY_SETTINGS'        => 'Valute'                      , 
	'LBL_CURRENCY_DESCRIPTION'     => 'Gestisce le valute internazionali e il tasso di conversione', 
	'LBL_CUSTOMIZE_MODENT_NUMBER'  => 'Personalizza la numerazione dei record', 
	'LBL_CUSTOMIZE_MODENT_NUMBER_DESCRIPTION' => 'Personalizzazione della numerazione delle entit&agrave;', 
	'LBL_MAIL_SCANNER'             => 'Mail Scanner'                , 
	'LBL_MAIL_SCANNER_DESCRIPTION' => 'Configura mailbox per scansionare', 
	'LBL_LIST_WORKFLOWS'           => 'Workflow'                    , 
	'LBL_LIST_WORKFLOWS_DESCRIPTION' => 'Crea e modifica i workflow per vtiger', 
	'Configuration Editor'         => 'Configuration Editor'        , 
	'Update configuration file of the application' => 'Update application configuration file', 
	'LBL_CUSTOMER_PORTAL'          => 'Portale Clienti'             , 
	'PORTAL_EXTENSION_DESCRIPTION' => 'Permette di configurare il plugin Portale Clienti', 
	'LBL_LAYOUT_EDITOR_DESCRIPTION' => 'Disegnare e modificare il layout in ciascun modulo', // TODO: Review
	'LBL_WEBFORMS_DESCRIPTION'     => 'Crea e gestisci webforms che possono essere usati per catturare lead', // TODO: Review
	'LBL_TO_ADD_NEW_USER_PLEASE_CLICK_ON' => 'Per aggiungere un nuovo utente, clicca su ', // TODO: Review
	'LBL_SETTINGS_ICON'            => 'Icona delle Impostazioni'               , // TODO: Review
	'LBL_ADD_OR_DELETE_USERS'      => 'Aggiungi/cancella utente'            , // TODO: Review
	'LBL_ADD_USER'                 => 'Aggiungi utente'                    , // TODO: Review
	'ModTracker'                   => 'Mod Tracker'                 , 
	'LBL_MODTRACKER_DESCRIPTION'   => 'Seleziona moduli da tracciare' , 
	'Scheduler'                    => 'Scheduler'                   , 
	'Allows you to Configure Cron Task' => 'Configura Cron Tasks'        , 
	'Webforms'                     => 'Webforms'                    , 
	'Allows you to manage Webforms' => 'Gestisci Webforms'             , 
	'LBL_CREATING_NEW'             => 'Creating new'                , // TODO: Review
	'LBL_EDITING'                  => 'Editing'                     , // TODO: Review
	'LBL_EDIT_RECORD'              => 'Modifica'                        , // TODO: Review
	'LBL_DELETE_RECORD'            => 'Cancella'                      , // TODO: Review
	'LBL_ADD_MOVE_MENU_ITEMS'      => 'Aggiungi/muovi oggetto menu'         , // TODO: Review
	'LBL_ADD_MENU_ITEM'            => 'Aggiungi oggetto menu'               , // TODO: Review
	'LBL_MAX'                      => 'Massimo'                         , // TODO: Review
	'LBL_TAX_CALCULATIONS'         => 'Calcolo tasse'            , // TODO: Review
	'LBL_TAX_DESC'                 => 'Gestisci tipi differenti di tasso delle tasse, come Tassa di Vendita, VAT ecc.,', // TODO: Review
	'LBL_PRODUCT_SERVICE_TAXES'    => 'Tasse di Prodotti e Servizi'     , // TODO: Review
	'LBL_SHIPPING_HANDLING_TAXES'  => 'Tasse di Spedizione e Gestione'   , // TODO: Review
	'LBL_ADD_NEW_TAX'              => 'Aggiungi Nuova Tassa'                 , // TODO: Review
	'LBL_EDIT_TAX'                 => 'Modifica Tassa'                    , // TODO: Review
	'LBL_TAX_NAME'                 => 'Nome Tassa'                    , // TODO: Review
	'LBL_TAX_VALUE'                => 'Valore Tassa'                   , // TODO: Review
	'LBL_STATUS'                   => 'Status'                      , // TODO: Review
	'LBL_TAX_STATUS_DESC'          => 'Flagga il riquadro di controllo per attivare la tassa', // TODO: Review
	'LBL_ENTER_TAX_NAME'           => 'Inserisci nome tassa'              , // TODO: Review
	'LBL_ENTER_TAX_VALUE'          => 'Inserisci valore tassa'             , // TODO: Review
	'LBL_TAX_NAME_EXIST'           => 'Nome tassa gi&agrave; esistente'     , // TODO: Review
	'LBL_TERMS_AND_CONDITIONS'     => 'Termine e Condizioni'          , // TODO: Review
	'LBL_SPECIFY_TERMS_AND_CONDITIONS' => 'Specificare Termini e Condizioni qui', // TODO: Review
	'LBL_ANNOUNCEMENTS'            => 'Annunci'               , // TODO: Review
	'LBL_ENTER_ANNOUNCEMENT_HERE'  => 'Inserisci Annunci qui'     , // TODO: Review
	'LBL_ANNOUNCEMENT_DESC'        => 'Cambia il testo che appare nella vista dell annuncio sopra ogni pagina', // TODO: Review
	'LBL_RESET_TO_DEFAULT'         => 'Riportare alle condizioni originali'            , // TODO: Review
	'LBL_SERVER_NAME'              => 'Nome Server'                 , // TODO: Review
	'LBL_USER_NAME'                => 'User Name'                   , // TODO: Review
	'LBL_PASSWORD'                 => 'Password'                    , // TODO: Review
	'LBL_FROM_EMAIL'               => 'Da Email'                  , // TODO: Review
	'LBL_REQUIRES_AUTHENTICATION'  => 'Richiedere autenticazione'     , // TODO: Review
	'LBL_OUTGOING_SERVER'          => 'Server in Uscita'             , // TODO: Review
	'LBL_OUTGOING_SERVER_DESC'     => 'Configurare le impostazioni del tuo server in uscita', // TODO: Review
	'LBL_DEFAULT'                  => 'Da predefinito, le impostazioni del account SMTP per il server in uscita sono configurate sul server mail od1.vtiger.com. Per evitare che le mail in uscita vadano nella cartella spam dal server ISP del tuo ricevente, raccomandiamo di implementare una delle seguenti.', // TODO: Review
	'LBL_OPTIONS1'                 => 'Mandare mail dal tuo mail server<br>
					- Inserire i dettagli del account SMTP (Nome Server, User Name, Password) per lo stesso account inserito nella indirizzo mail DA.', // TODO: Review
	'LBL_OPTIONS2'                 => 'Aggiungi il server od1.vtiger.com come un mittente autorizzato per il tuo dominio.<br>
					- Se si desidera mantenere il server vtiger come server in uscita, raccomandiamo di configurare il vostro dominio SPF record to include the vtiger server as a valid sender for your domain.
					  Per maggiori instruzioni su come configurare i record SPF, si prega di mandare mail a od-support@vtiger.com .', // TODO: Review
	'LBL_MAIL_SERVER_SMTP'         => 'Impostazioni del Server Mail (SMTP)' , // TODO: Review
	'LBL_OUTGOING_SERVER_FROM_FIELD' => 'NOTA: Se il campo "DA Email" &egrave; vuoto allora sara usato l\'indirizzo mail del utente.', // TODO: Review
	'LBL_TESTMAILSTATUS'           => 'Stato del Mail Test : '         , // TODO: Review
	'LBL_MAILSENDERROR'            => 'Il mail non si &egrave; inviato al utente admin. Si prega di verificare le impostazioni emailid/Server del admin', // TODO: Review
	'LBL_CONFIG_EDITOR'            => 'Editor della configurazone'        , // TODO: Review
	'LBL_CONFIG_DESCRIPTION'       => 'Modificare i dettagli della configurazione di vtiger CRM', // TODO: Review
	'LBL_CONFIG_FILE'              => 'config.inc.php'              , // TODO: Review
	'LBL_MB'                       => 'MB'                          , // TODO: Review
	'LBL_MINI_CALENDAR_DISPLAY'    => 'Display del mini Calendario'       , // TODO: Review
	'LBL_WORLD_CLOCK_DISPLAY'      => 'Display del orologio mondiale'         , // TODO: Review
	'LBL_CALCULATOR_DISPLAY'       => 'Display del calcolatore'          , // TODO: Review
	'LBL_USE_RTE'                  => 'Usa RTE'                     , // TODO: Review
	'LBL_HELPDESK_SUPPORT_EMAILID' => 'Email-Id del Supporto Helpdesk'   , // TODO: Review
	'LBL_HELPDESK_SUPPORT_NAME'    => 'Nome del Supporto Helpdesk'       , // TODO: Review
	'LBL_MAX_UPLOAD_SIZE'          => 'Dimensioni massime per il caricamento (Max 5MB)', // TODO: Review
	'LBL_MAX_HISTORY_VIEWED'       => 'Cronologia massiamo delle viste'      , // TODO: Review
	'LBL_DEFAULT_MODULE'           => 'Modulo Predefinito'              , // TODO: Review
	'LBL_MAX_TEXT_LENGTH_IN_LISTVIEW' => 'Lunghezza massima del testo nella Vista delle Liste', // TODO: Review
	'LBL_MAX_ENTRIES_PER_PAGE_IN_LISTVIEW' => 'Numero massimo di record per pagina nella Vista delle Liste', // TODO: Review
	'LBL_INVALID_EMAILID'          => 'EmailId non valido'             , // TODO: Review
	'LBL_INVALID_SUPPORT_NAME'     => 'Nome non valido'                , // TODO: Review
	'LBL_INVALID_MODULE'           => 'Modulo non valido'              , // TODO: Review
	'LBL_INVALID_NUMBER'           => 'Numero non valido'              , // TODO: Review
	'LBL_FIELDS_INFO_IS_EMPTY'     => 'Le informazioni campo sono vuote' , // TODO: Review
	'LBL_SUCCESSFULLY_UPDATED'     => 'Aggiornata con successo'        , // TODO: Review
	'LBL_CUSTOMIZE_RECORD_NUMBERING' => 'Personalizza la numerazione dei record'  , // TODO: Review
	'LBL_MODULE_ENTITY_NUMBER_CUSTOMIZATION' => 'Personalizzazione del numero di entita del Modulo', // TODO: Review
	'LBL_UPDATE_MISSING_RECORD_SEQUENCE' => 'Aggiorna la sequenza mancante dei record', // TODO: Review
	'LBL_USE_PREFIX'               => 'Usa prefisso'                  , // TODO: Review
	'LBL_START_SEQUENCE'           => 'Sequenza di Inizo'              , // TODO: Review
	'organizationname'             => 'Nome Azienda'                , // TODO: Review
	'logoname'                     => 'Logo Azienda'                , // TODO: Review
	'address'                      => 'Indirizzo'                     , // TODO: Review
	'city'                         => 'Citta'                        , // TODO: Review
	'state'                        => 'Stato'                       , // TODO: Review
	'code'                         => 'CAP'                 , // TODO: Review
	'country'                      => 'Provincia'                     , // TODO: Review
	'phone'                        => 'Telefono'                       , // TODO: Review
	'fax'                          => 'Fax'                         , // TODO: Review
	'website'                      => 'Sito Web'                     , // TODO: Review
	'LBL_INVALID_IMAGE'            => 'Immagine non valida'               , // TODO: Review
	'LBL_IMAGE_CORRUPTED'          => 'Virus intercettato o caricamento di una immagine corrotta', // TODO: Review
	'LBL_LOGO_RECOMMENDED_MESSAGE' => 'Le dimensioni raccomandate sono 170X60 pixels( .jpeg , .jpg , .png , .gif , .pjpeg , .x-png format ).', // TODO: Review
	'LBL_COMPANY_INFORMATION'      => 'Informazioni Azienda'         , // TODO: Review
	'LBL_UPDATE'                   => 'Aggiorna'                      , // TODO: Review
	'LBL_UPDATE_LOGO'              => 'Aggiorna Logo'                 , // TODO: Review
	'LBL_COMPANY_LOGO'             => 'Logo Azienda'                , // TODO: Review
	'LBL_EDIT_COMPANY_DETAILS_MESSAGE' => 'Per modificare i dettagli della azioenda si prega di selezionare l\'icona delle Impostazoni > Aggiungi/Cancella Utenti > Azienda ', // TODO: Review
	'LBL_ACTIVE'                   => 'Attivo'                      , // TODO: Review
	'LBL_INACTIVE'                 => 'In Attivo'                   , // TODO: Review
	'LBL_DISABLED'                 => 'Disabilitato'                    , // TODO: Review
	'LBL_RUNNING'                  => 'Funzionamento'                     , // TODO: Review
	'LBL_LAST_SCAN_TIMED_OUT'      => 'L\'ultimo scannerizzazione ha datto time-outLast scan timed out'         , // TODO: Review
	'LBL_LAST_SCAN_AT'             => 'L\'ultima scannerizzazione alle '            , // TODO: Review
	'LBL_TIME_TAKEN'               => ' tempo preso '                , // TODO: Review
	'LBL_SHORT_SECONDS'            => 'sec'                         , // TODO: Review
	
	//User Login History
	'LoginHistory' => 'Cronologia del Login degli Utenti',
	'LBL_LOGIN_HISTORY_DETAILS' => 'Cronologia del Login',
	'LBL_LOGIN_HISTORY_DESCRIPTION' => 'Dettagli Cronologia del Login',
	'LBL_USER_IP_ADDRESS'=> 'Indirizzo IP del utente',
	'LBL_LOGIN_TIME' => 'Tempo della entrata',
	'LBL_LOGGED_OUT_TIME' => 'Tempo della uscita',
);
$jsLanguageStrings = array(
	'JS_PLEASE_SELECT_ATLEAST_ONE_MEMBER_FOR_A_GROUP' => 'Si prega di selezionare almeno un utente per ogni gruppo', // TODO: Review
	'JS_GROUP_DELETED_SUCCESSFULLY' => 'Gruppo cancellato con successo'  , // TODO: Review
	'JS_TAX_SAVED_SUCCESSFULLY'    => 'Tassa salvata con successo'      , // TODO: Review
	'JS_TAX_DISABLED'              => 'Tassa disabilitatad'                , // TODO: Review
	'JS_TAX_ENABLED'               => 'Tassa attivata'                 , // TODO: Review
	'JS_EDIT'                      => 'Modifica'                        , // TODO: Review
	'JS_ANNOUNCEMENT_SAVED'        => 'Announcio Salvato'          , // TODO: Review
	'JS_CONFIRM_DEFAULT_SETTINGS'  => 'Sei sicuro di voler cambiare i dettagli del server con i valori predefiniti', // TODO: Review
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO5' => 'Si prega si inserire valora da 1 a 5', // TODO: Review
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO100' => 'Si prega si inserire valora da 1 a 100', // TODO: Review
	'JS_RECORD_NUMBERING_SAVED_SUCCESSFULLY_FOR' => 'Numerazione Record salvata con successo per', // TODO: Review
	'JS_RECORD_NUMBERING_UPDATED_SUCCESSFULLY_FOR' => 'Numerazione Record aggiornata con successo per', // TODO: Review
	'JS_SEQUENCE_NUMBER_MESSAGE'   => 'Sequenza numero deve esse pi&ugrave; grande o uguale a', // TODO: Review
	'LBL_WRONG_IMAGE_TYPE'         => 'Tipo immagine non supportata'    , // TODO: Review
	'LBL_MAXIMUM_SIZE_EXCEEDS'     => 'Si pu&ograve; caricare una dimesione massima di 1MB soltanto', // TODO: Review
	'LBL_NO_LOGO_SELECTED'         => 'Nessun logo selezionato'            , // TODO: Review
	'JS_CONFIGURATION_DETAILS_SAVED' => 'Dettagli della configurazione salvati' , // TODO: Review
);
