<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/

/* NOTE: Should be inline with Calendar language translation but few variations */

$languageStrings = array(
	'Activity Type'                => 'Tipo attivit&agrave;'        , 
	'Busy'                         => 'Occupato',
	'Call'                         => 'Chiamata'                    , 
	'Daily'                        => 'Giorno(i)'                   ,
	'End Date & Time'              => 'Data e ora fine'             , 
	'Events'                       => 'Eventi'                      , 
	'Held'                         => 'Tenuto'                      , 
	'INVITATION'		       => ' Invito '                    ,
	'LBL_ADD_RECORD'               => 'Aggiungi evento'             , 
	'LBL_CALENDAR_VIEW'            => 'Vista calendario'            , 
	'LBL_CREATE_FOLLOWUP_EVENT'    => 'Crea Evento Follow Up',
	'LBL_DAY0'                     => 'Domenica'                    ,
	'LBL_DAY1'                     => 'Luned&igrave;'               ,
	'LBL_DAY2'                     => 'Marted&igrave;'              ,
	'LBL_DAY3'                     => 'Mercoled&igrave;'            ,
	'LBL_DAY4'                     => 'Gioved&igrave;'              ,
	'LBL_DAY5'                     => 'Venerd&igrave;'              ,
	'LBL_DAY6'                     => 'Sabato'                      ,
	'LBL_DAY_OF_THE_MONTH'         => 'giorno del mese'             ,
	'LBL_DAYS'                     => 'Giorni'                      , 
	'LBL_DAYS_TYPE'                => 'Giorno(i)'                   ,
	'LBL_EVENT_INFORMATION'        => 'Dettagli evento'             , 
	'LBL_EVENTS'                   => 'Eventi'                      , 
	'LBL_FIRST'                    => 'Primo'                       ,
	'LBL_HOLD_FOLLOWUP_ON'         => 'Continua a seguire'          ,
	'LBL_HOURS'                    => 'Ore'                         , 
	'LBL_INVITE_USER_BLOCK'        => 'Invita'                      ,
	'LBL_INVITE_USERS'             => 'Invita utente'               ,
	'LBL_LAST'                     => 'Ultimo'                      ,
	'LBL_MONTHS_TYPE'              => 'Mese(i)'                     ,
	'LBL_ON'                       => 'su'                          ,
	'LBL_RECORDS_LIST'             => 'Lista eventi'                , 
	'LBL_RECURRENCE_INFORMATION'   => 'Dettagli ricorrenti'         , 
	'LBL_RELATED_TO'               => 'Relativo a'                  ,
	'LBL_REPEATEVENT'              => 'Ripeti ogni'                 ,
	'LBL_SM_FRI'                   => 'Ven'                         ,
	'LBL_SM_MON'                   => 'Lun'                         ,
	'LBL_SM_SAT'                   => 'Sab'                         ,
	'LBL_SM_SUN'                   => 'Dom'                         ,
	'LBL_SM_THU'                   => 'Gio'                         ,
	'LBL_SM_TUE'                   => 'Mar'                         ,
	'LBL_SM_WED'                   => 'Mer'                         ,
	'LBL_TODOS'                    => 'Compito'                     , 
	'LBL_UNTIL'                    => 'Fino'                        , 
	'LBL_WEEKS_TYPE'               => 'Settimana(e)'                ,
	'LBL_YEAR_TYPE'                => 'Anno'                        ,
	'Location'                     => 'Luogo'                       , 
	'Meeting'                      => 'Riunione'                    , 
	'Monthly'                      => 'Mese(i)'                     ,
	'Not Held'                     => 'Non Tenuto'                  , 
	'Planned'                      => 'Pianificato'                 , 
	'Private'                      => 'Privato'                     , 
	'Public'                       => 'Pubblico'                    , 
	'Recurrence'                   => 'Ricorrenza'                  , 
	'Send Notification'            => 'Invia notifica'              , 
	'Send Reminder'                => 'Invia promemoria'            , 
	'SINGLE_Events'                => 'Evento'                      , 
	'Start Date & Time'            => 'Data e ora inizio'           , 
	'Visibility'                   => 'Visibilit&agrave;'           , 
	'Weekly'                       => 'Settimana(e)'                ,
	'Yearly'                       => 'Anno(i)'                     ,
);
