<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'Big Problem'                  => 'Grosso problema'             , 
	'Closed'                       => 'Chiuso'                      , 
	'Contact Name'                 => 'Nome contatto'               ,
	'created'                      => 'creato', 
	'Critical'                     => 'Critica'                     , 
	'customer_portal'              => 'nel portale clienti di vTiger',
	'Days'                         => 'Giorni'                      , 
        'Dear'                         => 'Gentile',
	'Feature'                      => 'Caratteristica'              , 
	'From Portal'                  => 'Dal portale'                 , 
	'HelpDesk ID'                  => 'Ticket ID',
	'HelpDesk'                     => 'Assistenza clienti'          , 
	'High'                         => 'Alto'                        , 
	'Hi'                           => 'Salve',
	'Hours'                        => 'Orario'                      , 
	'LBL_ADD_RECORD'               => 'Aggiungi ticket'             , 
	'LBL_ALTBODY'                  => 'Questo &egrave; il corpo del messaggio in testo semplice per client di posta non-HTML',
	'LBL_CHECK_MAILID'             => 'Per cortesia controlla la tua e-mail  per il portale clienti',
	'LBL_CONVERT_FAQ'              => 'Converti in FAQ'             , 
	'LBL_COULDNOT_CLOSED'          => 'Non &egrave; stato possibile chiudere il ticket',
	'LBL_CUSTOMER_COMMENTS'        => 'Il cliente ha fornito le seguenti informazioni aggiuntive alla tua risposta:',
	'LBL_CUSTOMER_PORTAL'          => 'sul portale clienti - URGENTE',
	'LBL_DETAIL'                   => 'i dettagli sono :',
	'LBL_GIVE_MAILID'              => 'Prego inserire il tuo indirizzo e-mail',
	'LBL_LOGIN_DETAILS'            => 'Di seguito, i dettagli del tuo login al portale clienti:',
	'LBL_LOGIN_REVOKED'            => 'Il tuo login &egrave; stato revocato. Si prega di contattare l&#39;amministratore.',
	'LBL_MAIL_COULDNOT_SENT'       => 'Non &egrave; stato possibile inviare la mail',
	'LBL_MAIL_SENT'                => 'Una mail &egrave; stata inviata al tuo indirizzo di posta con i dettagli del tuo login al portale clienti',
	'LBL_PASSWORD'                 => 'Password :',
	'LBL_PORTAL_BODY_MAILINFO'     => 'Il ticket &egrave;',
	'LBL_RECORDS_LIST'             => 'Lista ticket'                , 
	'LBL_REGARDS'                  => 'Cordiali saluti',
	'LBL_RELATED_TO'               => 'Relazionato a'               ,
	'LBL_RESPOND'                  => 'Per cortesia rispondi al ticket qui sopra il prima possibile.',
	'LBL_RESPONDTO_TICKETID'       => 'Rispondi al ticket numero',
	'LBL_RESPONSE_TO_TICKET_NUMBER' => 'Risposta al biglietto numero',
	'LBL_SEVERITY'                 => 'Importanza'                  , 
	'LBL_STATUS_CLOSED'            => 'Closed',//Do not convert this label. This is used to check the status. If the status 'Closed' is changed in vtigerCRM server side then you have to change in customerportal language file also.
	'LBL_STATUS'                   => 'Stato'                       , 
	'LBL_STATUS_UPDATE'            => 'Lo stato del Ticket &egrave; aggiornato a',
	'LBL_SUBJECT_PORTAL_LOGIN_DETAILS' => 'Relativamente ai dettagli del tuo login al portale clienti',
	'LBL_SUBJECT'                  => 'Soggetto : ',
	'LBL_SUPPORT_ADMIN'            => 'Amministratore del supporto clienti',
	'LBL_TEAM'                     => 'Gruppo Assistenza Clienti',
	'LBL_TICKET_DETAILS'           => 'Dettaglio ticket',
	'LBL_TICKET_INFORMATION'       => 'Informazioni ticket'         , 
	'LBL_TICKET_NUMBER'            => 'Numero ticket',
	'LBL_TICKET_RESOLUTION'        => 'Informazioni soluzione'      , 
	'LBL_USERNAME'                 => 'Nome Utente :',
	'link'                         => 'Puoi usare il seguente link per visualizzare le risposte date:',
	'Major'                        => 'Maggiore'                    , 
	'Minor'                        => 'Minore'                      , 
	'Normal'                       => 'Normale'                     , 
	'Open'                         => 'Aperto'                      , 
	'Other Problem'                => 'Altro problema'              , 
	'Related To'                   => 'Nome Organizzazione'                ,
	'replied'                      => 'risposto',
	'reply'                        => '&egrave; presente una risposta a',
	'Re'                           => 'Re :',
	'Severity'                     => 'Importanza'                  , 
	'SINGLE_HelpDesk'              => 'Ticket'                      , 
	'Small Problem'                => 'Piccolo problema'            , 
	'Solution'                     => 'Soluzione'                   , 
	'Support_team'                 => 'Team di supporto vTiger',
	'Thanks'                       => 'Grazie',
	'The comments are'             => 'I commenti sono',
	'Ticket ID'                    =>'Ticket ID',
	'Ticket No'                    => 'Numero ticket'               , 
	'Ticket Title'                 => 'Titolo ticket',
	'Title'                        => 'Titolo'                      , 
	'Update History'               => 'Storico aggiornamenti'       , 
	'Urgent'                       => 'Urgente'                     , 
	'Wait For Response'            => 'In attesa risposta'          , 
);
