<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1'            => 'Step 1'                          , 
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'Seleziona file'                 , 
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	File supportati: .CSV, .VCF', 
	'LBL_IMPORT_STEP_2'            => 'Step 2'                          , 
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Specifica formato'              , 
	'LBL_FILE_TYPE'                => 'Tipologia file'                  , 
	'LBL_CHARACTER_ENCODING'       => 'Codifica carattere'              , 
	'LBL_DELIMITER'                => 'Delimitatore:'                   , 
	'LBL_HAS_HEADER'               => 'Ha un header (intestazione)'     , 
	'LBL_IMPORT_STEP_3'            => 'Step 3'                          , 
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'Gestione elementi duplicati'      , 
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Seleziona questa opzione per permettere e impostare i criteri di unione duplicati', 
	'LBL_SPECIFY_MERGE_TYPE'       => 'Seleziona come devono essere gestiti gli elementi duplicati', 
	'LBL_SELECT_MERGE_FIELDS'      => 'Seleziona i campi corrispondenti per cercare gli elementi duplicati', 
	'LBL_AVAILABLE_FIELDS'         => 'Campi disponibili'               , 
	'LBL_SELECTED_FIELDS'          => 'Campi con cui cercare una corrispondenza', 
	'LBL_NEXT_BUTTON_LABEL'        => 'Prossimo'                        , 
	'LBL_IMPORT_STEP_4'            => 'Step 4'                          , 
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Mappa le colonne dei campi modulo', 
	'LBL_FILE_COLUMN_HEADER'       => 'Intestazione'                    , 
	'LBL_ROW_1'                    => 'Riga 1'                          , 
	'LBL_CRM_FIELDS'               => 'Campi CRM'                       , 
	'LBL_DEFAULT_VALUE'            => 'Valore predefinito'              , 
	'LBL_SAVE_AS_CUSTOM_MAPPING'   => 'Salva come mappatura personalizzata' , 
	'LBL_IMPORT_BUTTON_LABEL'      => 'Importa'                         , 
	'LBL_RESULT'                   => 'Risultato'                       , 
	'LBL_TOTAL_RECORDS_IMPORTED'   => 'Elementi importati con successo' , 
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'Elementi creati'                , 
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'Elementi sovrascritti'          , 
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'Elementi saltati'               , 
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'Elementi uniti'                  , 
	'LBL_TOTAL_RECORDS_FAILED'     => 'Fallita importazione elementi'   , 
	'LBL_IMPORT_MORE'              => 'Importa di pi&ugrave;'           , 
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'Ultimi elementi importati'     , 
	'LBL_UNDO_LAST_IMPORT'         => 'Annulla l\'importazione appena completata'  , 
	'LBL_FINISH_BUTTON_LABEL'      => 'Fine'                            , 
	'LBL_UNDO_RESULT'              => 'Annulla risultato importazione'  , 
	'LBL_TOTAL_RECORDS'            => 'Numero totale elementi'          , 
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'Numero di elementi cancellati'  , 
	'LBL_OK_BUTTON_LABEL'          => 'Ok'                              , 
	'LBL_IMPORT_SCHEDULED'         => 'Importazione programmata'        , 
	'LBL_RUNNING'                  => 'Caricamento'                     , 
	'LBL_CANCEL_IMPORT'            => 'Cancella importazione'           , 
	'LBL_ERROR'                    => 'Errore'                          , 
	'LBL_CLEAR_DATA'               => 'Elimina i dati'                  , 
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'Impossibile importare altri dati in questo processo. Inizia una nuova importazione.', 
	'ERR_IMPORT_INTERRUPTED'       => 'L&acute;importazione corrente &egrave; stata interrota. Riprova pi&ugrave; tardi', 
	'ERR_FAILED_TO_LOCK_MODULE'    => 'Impossibile bloccare il modulo per l&acute;importazione. Riprova pi&ugrave; tardi', 
	'LBL_SELECT_SAVED_MAPPING'     => 'Seleziona mappatura salvata'     , 
	'LBL_IMPORT_ERROR_LARGE_FILE'  => 'Errore di importazione file troppo grande ' ,
	'LBL_FILE_UPLOAD_FAILED'       => 'Caricamento file fallito'        ,
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'L&acute;importazione ha cambiato la dimensione del file ' , 
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'La cartella di importazione non &egrave; scrivibile' , 
	'LBL_IMPORT_FILE_COPY_FAILED'  => 'Copia del file di importazione fallita' ,
	'LBL_INVALID_FILE'             => 'Nome file invalido'              , 
	'LBL_NO_ROWS_FOUND'            => 'Nessuna riga trovata'            ,
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'Importazione programmata e inizier&agrave; entro 15 minuti. Riceverai un email dopo che sar&agrave; completata.  <br> <br>
										Assicurati che il server in uscita a il tuo indirizzo email sia configurato per ricevere le notifiche', 
	'LBL_DETAILS'                  => 'Dettagli'                        , 
	'skipped'                      => 'Elementi saltati'                , 
	'failed'                       => 'Elementi falliti'                ,
        'Skip'                         => 'Salta',
        'Overwrite'                    => 'Sovrascrivere',
        'Merge'                        => 'Unire',
);
